# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller spec for BabelChat single binary (Linux)."""
a = Analysis(
    ["app/main.py"],
    pathex=["."],
    binaries=[('app/libbabelchat_scanner.so', '.')],
    datas=[
        ("assets/icon.png", "assets"),
        ("addon/BabelChat", "addon/BabelChat"),
    ],
    hiddenimports=[
        "lingua",
        "lingua.builder",
        "deepl",
        "watchdog",
        "watchdog.observers",
        "watchdog.events",
        "PyQt6",
        "PyQt6.QtCore",
        "PyQt6.QtGui",
        "PyQt6.QtWidgets",
        "dotenv",
        "app.watcher",
        "app.parser",
        "app.detector",
        "app.translator",
        "app.cache",
        "app.pipeline",
        "app.overlay",
        "app.tray",
        "app.config",
        "app.settings_dialog",
        "app.setup_wizard",
        "app.about_dialog",
        "app.reply_widget",
        "app.lang_selector",
        "app.hotkeys",
        "app.hotkeys_linux",
        "app.text_utils",
        "app.memory_reader",
        "app.memory_reader_linux",
        "app.i18n",
        "app.phrasebook",
        "app.slang",
        "pynput",
        "pynput.keyboard",
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        "tkinter",
        "matplotlib",
        "numpy",
        "scipy",
        "PIL",
        "pymem",
        "pymem.process",
        "pymem.exception",
        "app.memory_reader_windows",
        "app.hotkeys_windows",
    ],
    noarchive=False,
)
pyz = PYZ(a.pure)
exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name="BabelChat",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    icon="assets/icon.png",
    onefile=True,
)